
# Adjust these as needed
CXX = icpc
CXXFLAGS = -std=c++11 -O3 -g -fPIC -xcore-avx2 -axmic-avx512 -pthread -qopenmp -DHAVE_MKL
LDFLAGS =
LINK = -qopenmp -lmkl_rt -liomp5 -lpthread -limf -lsvml -ldl

OBJS = toast_pointing.o pointing_openmp.o utils.o
HEADERS = utils.hpp pointing_openmp.hpp


all : toast_pointing

toast_pointing : $(OBJS)
	$(CXX) $(LDFLAGS) -o $@ $(OBJS) $(LINK)

%.o : %.cpp $(HEADERS)
	$(CXX) $(CXXFLAGS) -I. -o $@ -c $<

clean :
	rm -f toast_pointing *.o
